// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateMessageMessagesPostData, CreateMessageMessagesPostErrors, CreateMessageMessagesPostResponses, DeleteConversationConversationsConversationIdDeleteData, DeleteConversationConversationsConversationIdDeleteErrors, DeleteConversationConversationsConversationIdDeleteResponses, ListConversationsConversationsGetData, ListConversationsConversationsGetResponses, ListMessagesConversationsConversationIdMessagesGetData, ListMessagesConversationsConversationIdMessagesGetErrors, ListMessagesConversationsConversationIdMessagesGetResponses, ListModelsModelsGetData, ListModelsModelsGetResponses, RenameConversationConversationsConversationIdPatchData, RenameConversationConversationsConversationIdPatchErrors, RenameConversationConversationsConversationIdPatchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Models
 */
export const listModelsModelsGet = <ThrowOnError extends boolean = false>(options?: Options<ListModelsModelsGetData, ThrowOnError>) => (options?.client ?? client).get<ListModelsModelsGetResponses, unknown, ThrowOnError>({ url: '/models', ...options });

/**
 * Create Message
 */
export const createMessageMessagesPost = <ThrowOnError extends boolean = false>(options: Options<CreateMessageMessagesPostData, ThrowOnError>) => (options.client ?? client).post<CreateMessageMessagesPostResponses, CreateMessageMessagesPostErrors, ThrowOnError>({
    url: '/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Conversations
 */
export const listConversationsConversationsGet = <ThrowOnError extends boolean = false>(options?: Options<ListConversationsConversationsGetData, ThrowOnError>) => (options?.client ?? client).get<ListConversationsConversationsGetResponses, unknown, ThrowOnError>({ url: '/conversations', ...options });

/**
 * List Messages
 */
export const listMessagesConversationsConversationIdMessagesGet = <ThrowOnError extends boolean = false>(options: Options<ListMessagesConversationsConversationIdMessagesGetData, ThrowOnError>) => (options.client ?? client).get<ListMessagesConversationsConversationIdMessagesGetResponses, ListMessagesConversationsConversationIdMessagesGetErrors, ThrowOnError>({ url: '/conversations/{conversation_id}/messages', ...options });

/**
 * Delete Conversation
 */
export const deleteConversationConversationsConversationIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteConversationConversationsConversationIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteConversationConversationsConversationIdDeleteResponses, DeleteConversationConversationsConversationIdDeleteErrors, ThrowOnError>({ url: '/conversations/{conversation_id}', ...options });

/**
 * Rename Conversation
 */
export const renameConversationConversationsConversationIdPatch = <ThrowOnError extends boolean = false>(options: Options<RenameConversationConversationsConversationIdPatchData, ThrowOnError>) => (options.client ?? client).patch<RenameConversationConversationsConversationIdPatchResponses, RenameConversationConversationsConversationIdPatchErrors, ThrowOnError>({
    url: '/conversations/{conversation_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
