// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_rename_conversation_conversations__conversation_id__patch
 */
export type BodyRenameConversationConversationsConversationIdPatch = {
    /**
     * Title
     */
    title: string;
};

/**
 * Conversation
 */
export type Conversation = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Title
     */
    title: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Conversation Id
     */
    conversation_id: string | null;
    /**
     * Created At
     */
    created_at?: string;
    role: Role;
    /**
     * Content
     */
    content: string;
};

/**
 * MessageRequest
 */
export type MessageRequest = {
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Model Source
     */
    model_source: string;
    /**
     * Model
     */
    model: string;
    reasoning_effort?: ReasoningEffort;
};

/**
 * ReasoningEffort
 */
export type ReasoningEffort = 'low' | 'medium' | 'high';

/**
 * Role
 */
export type Role = 'user' | 'assistant';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListLlmsModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/models';
};

export type ListLlmsModelsGetResponses = {
    /**
     * Response List Llms Models Get
     *
     * Successful Response
     */
    200: {
        [key: string]: Array<string>;
    };
};

export type ListLlmsModelsGetResponse = ListLlmsModelsGetResponses[keyof ListLlmsModelsGetResponses];

export type CreateMessageMessagesPostData = {
    body: MessageRequest;
    path?: never;
    query?: never;
    url: '/messages';
};

export type CreateMessageMessagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMessageMessagesPostError = CreateMessageMessagesPostErrors[keyof CreateMessageMessagesPostErrors];

export type CreateMessageMessagesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListConversationsConversationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/conversations';
};

export type ListConversationsConversationsGetResponses = {
    /**
     * Response List Conversations Conversations Get
     *
     * Successful Response
     */
    200: Array<Conversation>;
};

export type ListConversationsConversationsGetResponse = ListConversationsConversationsGetResponses[keyof ListConversationsConversationsGetResponses];

export type ListMessagesConversationsConversationIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/conversations/{conversation_id}/messages';
};

export type ListMessagesConversationsConversationIdMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesConversationsConversationIdMessagesGetError = ListMessagesConversationsConversationIdMessagesGetErrors[keyof ListMessagesConversationsConversationIdMessagesGetErrors];

export type ListMessagesConversationsConversationIdMessagesGetResponses = {
    /**
     * Response List Messages Conversations  Conversation Id  Messages Get
     *
     * Successful Response
     */
    200: Array<Message>;
};

export type ListMessagesConversationsConversationIdMessagesGetResponse = ListMessagesConversationsConversationIdMessagesGetResponses[keyof ListMessagesConversationsConversationIdMessagesGetResponses];

export type DeleteConversationConversationsConversationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}';
};

export type DeleteConversationConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationConversationsConversationIdDeleteError = DeleteConversationConversationsConversationIdDeleteErrors[keyof DeleteConversationConversationsConversationIdDeleteErrors];

export type DeleteConversationConversationsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenameConversationConversationsConversationIdPatchData = {
    body: BodyRenameConversationConversationsConversationIdPatch;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}';
};

export type RenameConversationConversationsConversationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenameConversationConversationsConversationIdPatchError = RenameConversationConversationsConversationIdPatchErrors[keyof RenameConversationConversationsConversationIdPatchErrors];

export type RenameConversationConversationsConversationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
